version: '3.9'

networks:

  db_network:
    external: false

services:

  postgres-db:
    image: postgres:16.1
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_INITDB_ARGS: "-A md5"
      USER_UID: 1000
      USER_GID: 1000
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    networks:
      - db_network

  flask:
    container_name: flask_app
    build: ./flask-app
    command: python app.py run
    volumes:
      - ./flask-app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      - db_network
    depends_on:
      - postgres-db
