version: '3.9'

networks:

  db_network:
    external: false

services:
# создать папку postgres-db
  postgres-db:
    image: postgres:16.1
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    networks:
      - db_network

  flask:
    container_name: web
    build: ./web_app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web_app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    networks:
      - db_network
    depends_on:
      - postgres-db
